### ISSUE TITLE
...

### ISSUE THREAD

**Issue by syw0919** [lucas-park/HangulCaesarCipher#1]
![キャプチャ](https://user-images.githubusercontent.com/44917049/66707943-c39f3380-ed83-11e9-8b4e-975cd7413c6f.PNG)

**Comment by syw0919** [comment]
간단히 코드를 봤는데 말이죠 오전 4시 30분에 충혈된 눈을 비비며 무리한 야근에 제대로 돌아가지도 않는 머리로 간신히 짰으나 이거 수정했다가 저거 수정했다가 하면서 코드를 너무 왔다갔다 하는 바람에 적어놓지 않고 기억에만 저장해놓은 수정사항들이 미처 떠오르지 못해 제대로 수정도 마치지 않고 릴리즈한 것 마냥 생겼더군요
한마디로 말해서 버그 덩어리

**Comment by syw0919** [comment]
decrypt 시 헤더 포함 여부에 따라 복호화 하도록 설정 바람

**Comment by lucas-park** [comment]
지금까지 한글 카이사르 프로그램을 이용해 주신 것에 감사드립니다. 복호화 헤더 상태 버그, 유니코드 디코딩 버그 때문에 @syw0919 께서 프로그램을 원활하게 사용하지 못하게 된 것을 유감으로 생각합니다.

지금 막 해당 버그를 수정하는 패치 코드를 커밋하였습니다. 이러한 버그를 미리 인지하고 있지 못한 점 사과드리며, 앞으로도 이러한 문제가 생길 경우 연락해 주시기 바랍니다. 바쁘신데 방해가 된 건 아닌지 모르겠네요.
